### ISSUE TITLE
How to receive notification through firebase?

### ISSUE THREAD

**Issue by iarmankhan** [cryptoticket/react-native-push-notification#1]
Hey, I implemented this library and it's working very fine for local notification, but how can I receive notification from firebase (You've already mentioned to copy google-service.json) so what's the use of that in here?
Can you please provider some guidance to implement some kind of listener to listen to notification sent from firebase?
Thank you.

**Comment by ryzhak** [comment]
@iarmankhan 

>  how can I receive notification from firebase

Follow these steps https://github.com/cryptoticket/react-native-push-notification#how-to-install and your app should be able to receive remote push notifications automatically.

> Can you please provider some guidance to implement some kind of listener to listen to notification sent from firebase

There is **no** any kind of *onNotification()* handler in this package. You can show local notifications via the `show()` method and remote notifications from firebase are displayed automatically. You can:
- override `CustomFirebaseMessagingService` with your own service 
- listen for notifications there and send notification events to JS ([how to do it](https://facebook.github.io/react-native/docs/native-modules-android#sending-events-to-javascript)) 

You may find twilio example of overriding `CustomFirebaseMessagingService` in the "troubleshooting" [section](https://github.com/cryptoticket/react-native-push-notification#troubleshooting). And still need to send notification events to JS.

**Comment by iarmankhan** [comment]
Hey, I ran the example app you've given, it worked fine for local notification, I created an app in firebase & copied my google-service.json to app folder. After going to "cloud-messaging" and sending test message, I still didn't get any notification in app. Can you explain me how to do that? Although local notifications are working correctly.

**Comment by ryzhak** [comment]
@iarmankhan 

When you create `google-services.json` file in firebase I think the only condition is to set `com.example` as package name and app in the `example` folder should work out of the box(for remote notification sent from firebase console).

**Comment by iarmankhan** [comment]
![image](https://user-images.githubusercontent.com/40450695/72976667-077cec80-3df9-11ea-8797-b6d4aa520b62.png)
As you can see, I've already specified the package name, before generating the json file. 
![image](https://user-images.githubusercontent.com/40450695/72976748-2e3b2300-3df9-11ea-9bf2-3b225034ad64.png)
But as you can see I never received any notification, if app is in foreground or in background.

**Comment by iarmankhan** [comment]
Hey, I just remove node_modules and re-built the app again and it's working now! Thank you! Sorry for any trouble caused by me!
