### ISSUE TITLE
How to send image through FCM send API?

### ISSUE THREAD

**Issue by iarmankhan** [cryptoticket/react-native-push-notification#2]
Hey, so I successfully received firebase notifications from console, now I'm creating a web app to send notification from there. 
I used the FCM send API to send notification and it worked perfectly, I received notification on multiple devices.
Now whenever I try to send notification with image, it only show text notifcation.

![image](https://user-images.githubusercontent.com/40450695/73117614-50a27d00-3f6e-11ea-90be-416bdacb0a44.png)

My Current API payload:
```
Uri: https://fcm.googleapis.com/fcm/send
Headers: 
Content-Type: application/json
Authorization: key=xxxxxxxxxx

Body: 
{
     "registration_ids": [
            "xxxxxxxdevice_tokenxxxxx"
       ],
     "data" : {
            "title": "Test Notification",
            "message" : "Noti from FCM",
            "image" : "image_url",
      }
}
```

I've also tried using "main_picture" instead of "image" in data object.
After searching on stackoverflow I found that you have to attach image manually in notification but I've received image notification from firebase console.
So what's wrong here?
Thank you!

**Comment by ryzhak** [comment]
@iarmankhan 

Check this section https://github.com/cryptoticket/react-native-push-notification#correct-way-to-send-push-notifications-from-server

Image url should be passed in `media` data attribute.

Try:
```
Body: 
{
     "registration_ids": [
            "xxxxxxxdevice_tokenxxxxx"
       ],
     "data" : {
            "title": "Test Notification",
            "message" : "Noti from FCM",
            "media" : "image_url",
      }
}
```

**Comment by iarmankhan** [comment]
Thank you, it's working fine!
