### ISSUE TITLE
Modifying template "notification_template_event.xml" causing build to fail

### ISSUE THREAD

**Issue by iarmankhan** [cryptoticket/react-native-push-notification#4]
Hello,
I tried to remove the black button with a checkmark from "notification_template_event.xml" file. After saving the file, I ran run-android command and it gave me following errors:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rnPushNotification:compileDebugKotlin'.
> Compilation error. See log for more details
```

I tried undoing all my changes and it worked fine. Can you please help me with this? I don't want to create a new template yet, just want to modify this one to remove checkmark (just to have more space for notification and image)

**Comment by iarmankhan** [comment]
After some searching through android folder, I found out that checkmark button is being used in Kotlin files, maybe that's causing errors. 

Do you have some pre-made templates or are you going to add any in future release? Thanks.

**Comment by ryzhak** [comment]
Hello, @iarmankhan 

`I tried undoing all my changes and it worked fine. Can you please help me with this? I don't want to create a new template yet,`
You have got 2 options:
1. Create a new template without the checkbox button. [How to add a new template](https://github.com/cryptoticket/react-native-push-notification#how-to-add-a-custom-template-to-this-repository). PRs are very welcome!
2. Wait some time(~month), we have plans to remove this checkmark from event notification template in our app so this repository will be updated.

`Are expandable notifications (for image) coming in future release? `
At the moment we don`t plan adding new templates. Again, PRs are always welcome.

**Comment by iarmankhan** [comment]
Hey @ryzhak 

I followed your guide and removed the checkmark from event template. Also I don't alot about kotlin or android in general so I can PR for expandable notifications but I'll surely look into that matter. BTW nice work. This is the only library that worked perfectly for me.

I'll open a PR for removing checkmark from event template after some minor layout related fixes. 
Thank you for your time. Looking forward for more amazing updates.

**Comment by ryzhak** [comment]
@iarmankhan 

> I'll open a PR for removing checkmark from event template after some minor layout related fixes

ok, waiting for it, thank you

> This is the only library that worked perfectly for me
good to hear
